name: 自动生成去广告规则
on:
  push:
    branches:
      - master
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install requests
      - run: python3 miui_adblack.py

      - uses: actions/upload-artifact@v1
        with:
          name: mmiui_adblocklist
          path: ${{ github.workspace }}/miui_blacklist.json


