name: Schedule Worker
on:
  push:
    # 分支随意
    branches:
      - master
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 # 使用python装配器
        with:
          python-version: '3.10' # 指定python版本
          cache: 'poetry' # 设置缓存

      - run: poetry install --requests
      - run: poetry run python ./miui_adblack

